/// Flutter icons CustomIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData bellpepper = IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tomato = IconData(0xe901, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData strawberry = IconData(0xe902, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
