/// Flutter icons Customicons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Customicons
///      fonts:
///       - asset: fonts/Customicons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Customicons {
  Customicons._();

  static const _kFontFam = 'Customicons';
  static const String? _kFontPkg = null;

  static const IconData fruit_food_apple_svgrepo_com = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fruit_grape_grapes_svgrepo_com = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grape_berry_svgrepo_com = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grape_svgrepo_com = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instacart_svgrepo_com = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData johndeere_svgrepo_com = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData leaflet_svgrepo_com = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData orange_citrus_fresh_fruit_healthy_food_svgrepo_com = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pear_svgrepo_com = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pepper_hot_svgrepo_com = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rice_grain_svgrepo_com = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData strawberry_svgrepo_com = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vegetable_food_carrot_svgrepo_com = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vegetable_food_garlic_svgrepo_com = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple_black_fruit_shape_svgrepo_com = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple_cooking_food_2_svgrepo_com = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple_fresh_fruit_svgrepo_com = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple_fruit_svgrepo_com = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bananas_svgrepo_com = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_capsicum_pepper_svgrepo_com = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cantaloupe_fruit_melon_svgrepo_com = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cherry_fruit_berry_svgrepo_com = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chili_chilli_pepper_svgrepo_com = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData citrus_fresh_fruit_svgrepo_com = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData citrus_fruits_svgrepo_com = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fragaria_fruit_strawberry_svgrepo_com = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fresh_fruit_svgrepo_com = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fresh_tomato_tomatoes_svgrepo_com = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
